# Generated by Django 5.0.2 on 2024-02-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.TextField()),
                ('account_id', models.TextField()),
                ('device_id', models.TextField()),
                ('device_name', models.TextField()),
                ('rule_id', models.TextField()),
                ('alarm_id', models.TextField()),
                ('alarm_name', models.TextField()),
                ('description', models.TextField()),
                ('state', models.TextField()),
                ('duration', models.TextField()),
                ('created_at', models.TextField()),
                ('finalized_at', models.TextField()),
                ('severity', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
